// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceId } from "./WorkspaceId";

export type ActiveWorkspace = { id: WorkspaceId, path: string, name: string, opened_at: string, };
