// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InkTool } from "./InkTool";
import type { StrokeAnchor } from "./StrokeAnchor";
import type { StrokeId } from "./StrokeId";
import type { StrokePoint } from "./StrokePoint";

export type AnchoredStroke = { id: StrokeId, points: Array<StrokePoint>, color: string, size: number, tool: InkTool, opacity: number, timestamp: bigint, anchor: StrokeAnchor | null, };
