// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActiveWorkspace } from "./ActiveWorkspace";
import type { GlobalSettings } from "./GlobalSettings";
import type { RecentWorkspace } from "./RecentWorkspace";
import type { WorkspaceId } from "./WorkspaceId";

export type AppState = { schema_version: number, recent_workspaces: Array<RecentWorkspace>, active_workspaces: Array<ActiveWorkspace>, focused_workspace_id: WorkspaceId | null, last_opened_workspace: string | null, global_settings: GlobalSettings, };
