// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalSettings } from "./GlobalSettings";
import type { RecentWorkspace } from "./RecentWorkspace";

export type AppState = { recent_workspaces: Array<RecentWorkspace>, last_opened_workspace: string | null, global_settings: GlobalSettings, };
