// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalloutBlock } from "./CalloutBlock";
import type { ChecklistBlock } from "./ChecklistBlock";
import type { CodeBlock } from "./CodeBlock";
import type { DividerBlock } from "./DividerBlock";
import type { EmbedBlock } from "./EmbedBlock";
import type { ImageBlock } from "./ImageBlock";
import type { InkBlock } from "./InkBlock";
import type { MarkdownBlock } from "./MarkdownBlock";
import type { PdfBlock } from "./PdfBlock";
import type { TableBlock } from "./TableBlock";
import type { TextBlock } from "./TextBlock";

export type Block = { "type": "text" } & TextBlock | { "type": "markdown" } & MarkdownBlock | { "type": "code" } & CodeBlock | { "type": "checklist" } & ChecklistBlock | { "type": "table" } & TableBlock | { "type": "image" } & ImageBlock | { "type": "ink" } & InkBlock | { "type": "pdf" } & PdfBlock | { "type": "divider" } & DividerBlock | { "type": "callout" } & CalloutBlock | { "type": "embed" } & EmbedBlock;
