// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockId } from "./BlockId";
import type { CalloutVariant } from "./CalloutVariant";

export type CalloutBlock = { variant: CalloutVariant, content: string, id: BlockId, order: number, created_at: string, updated_at: string, };
