// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockId } from "./BlockId";
import type { ChecklistItem } from "./ChecklistItem";

export type ChecklistBlock = { items: Array<ChecklistItem>, id: BlockId, order: number, created_at: string, updated_at: string, };
