// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockId } from "./BlockId";

export type EmbedBlock = {
  url: string;
  title: string | null;
  description: string | null;
  thumbnail: string | null;
  id: BlockId;
  order: number;
  created_at: string;
  updated_at: string;
};
