// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Language } from "./Language";
import type { ThemeConfig } from "./ThemeConfig";
import type { WindowBounds } from "./WindowBounds";

export type GlobalSettings = { theme: ThemeConfig, language: Language, window_bounds: WindowBounds | null, };
