// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotationId } from "./AnnotationId";
import type { BlockId } from "./BlockId";

export type HighlightAnnotation = { id: AnnotationId, block_id: BlockId, start_offset: number, end_offset: number, color: string, opacity: number, };
