// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from "./Block";
import type { EditorPreferences } from "./EditorPreferences";
import type { TemplateCategory } from "./TemplateCategory";
import type { TemplateId } from "./TemplateId";

export type NoteTemplate = { id: TemplateId, name: string, description: string | null, category: TemplateCategory, icon: string | null, 
/**
 * Título sugerido ao criar page. Suporta placeholder {{date}}.
 */
title_template: string, tags: Array<string>, blocks: Array<Block>, editor_preferences: EditorPreferences, is_builtin: boolean, created_at: string, updated_at: string, schema_version: number, };
