// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { NotebookId } from "./NotebookId";

export type Notebook = {
  id: NotebookId;
  name: string;
  color: Color | null;
  icon: string | null;
  order: number;
  created_at: string;
  updated_at: string;
};
