// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncryptionAlgorithm } from "./EncryptionAlgorithm";
import type { KdfParams } from "./KdfParams";
import type { KeyDerivationFunction } from "./KeyDerivationFunction";

export type PageProtection = { algorithm: EncryptionAlgorithm, kdf: KeyDerivationFunction, kdf_params: KdfParams, salt: string, nonce: string, };
