// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageId } from "./PageId";

export type PageSummary = {
  id: PageId;
  title: string;
  tags: Array<string>;
  block_count: number;
  created_at: string;
  updated_at: string;
};
