// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnchoredStroke } from "./AnchoredStroke";
import type { HighlightAnnotation } from "./HighlightAnnotation";

export type PageAnnotations = {
  strokes: Array<AnchoredStroke>;
  highlights: Array<HighlightAnnotation>;
  svg_cache: string | null;
};
