// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockId } from "./BlockId";

export type PdfBlock = { src: string, total_pages: number, id: BlockId, order: number, created_at: string, updated_at: string, };
