// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { NotebookId } from "./NotebookId";
import type { SectionId } from "./SectionId";

export type Section = { id: SectionId, notebook_id: NotebookId, name: string, color: Color | null, order: number, created_at: string, updated_at: string, };
