// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockId } from "./BlockId";

export type StrokeAnchor = { block_id: BlockId, offset_x: number, offset_y: number, pdf_page: number | null, };
