// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockId } from "./BlockId";

export type TableBlock = { rows: Array<Array<string>>, has_header: boolean, id: BlockId, order: number, created_at: string, updated_at: string, };
