// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateCategory } from "./TemplateCategory";
import type { TemplateId } from "./TemplateId";

export type TemplateSummary = { id: TemplateId, name: string, description: string | null, category: TemplateCategory, icon: string | null, title_template: string, is_builtin: boolean, block_count: number, created_at: string, };
