// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseTheme } from "./BaseTheme";
import type { ChromeTint } from "./ChromeTint";

export type ThemeConfig = { base_theme: BaseTheme, accent_color: string, chrome_tint: ChromeTint, };
