// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrashItemType } from "./TrashItemType";

export type TrashItem = { id: string, item_type: TrashItemType, original_title: string, original_path: string, original_notebook: string, original_section: string | null, deleted_at: string, expires_at: string, size_bytes: bigint, };
