// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotebookId } from "./NotebookId";
import type { PageId } from "./PageId";
import type { SectionId } from "./SectionId";

export type WorkspaceSettings = { default_notebook_id: NotebookId | null, auto_save_interval_ms: bigint, sidebar_width: number, sidebar_open: boolean, last_opened_page_id: PageId | null, quick_notes_notebook_id: NotebookId | null, quick_notes_section_id: SectionId | null, };
