// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceId } from "./WorkspaceId";
import type { WorkspaceSettings } from "./WorkspaceSettings";

export type Workspace = {
  id: WorkspaceId;
  name: string;
  root_path: string;
  created_at: string;
  updated_at: string;
  settings: WorkspaceSettings;
};
