// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpellCheckMatch } from "./SpellCheckMatch";

export type SpellCheckResponse = { matches: Array<SpellCheckMatch>, language: string, };
