// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpellCheckMatch = { message: string, offset: number, length: number, replacements: Array<string>, rule_id: string, rule_description: string, category: string, };
